const STICKER_LIBRARY = {
  flowers: [
    { content: '🌹', type: 'emoji', name: 'Rose' },
    { content: '🌸', type: 'emoji', name: 'Cherry Blossom' },
    { content: '🌺', type: 'emoji', name: 'Hibiscus' },
    { content: '🌻', type: 'emoji', name: 'Sunflower' },
    { content: '🌼', type: 'emoji', name: 'Daisy' },
    { content: '🌷', type: 'emoji', name: 'Tulip' },
    { content: '🪷', type: 'emoji', name: 'Lotus' },
    { content: '💐', type: 'emoji', name: 'Bouquet' },
    { content: '🏵️', type: 'emoji', name: 'Rosette' },
    { content: '💮', type: 'emoji', name: 'White Flower' },
    { content: '🥀', type: 'emoji', name: 'Wilted Flower' },
    { content: '☘️', type: 'emoji', name: 'Shamrock' },
    { content: '🍀', type: 'emoji', name: 'Four Leaf Clover' },
    { content: '🪴', type: 'emoji', name: 'Potted Plant' },
    { content: '🌵', type: 'emoji', name: 'Cactus' },
    { content: '🌴', type: 'emoji', name: 'Palm Tree' },
    { content: '🌱', type: 'emoji', name: 'Seedling' },
    { content: '🌿', type: 'emoji', name: 'Herb' },
    { content: '🍁', type: 'emoji', name: 'Maple Leaf' },
    { content: '🍃', type: 'emoji', name: 'Leaf Fluttering in Wind' },
    { content: '🍄', type: 'emoji', name: 'Mushroom' },
    { content: '🌾', type: 'emoji', name: 'Sheaf of Rice' },
    { content: '🎋', type: 'emoji', name: 'Tanabata Tree' },
    { content: '🍃', type: 'emoji', name: 'Leaves' },
    { content: '🥀', type: 'emoji', name: 'Withered Rose' },
    { content: '🍂', type: 'emoji', name: 'Fallen Leaf' },
    { content: '🍎', type: 'emoji', name: 'Red Apple' },
    { content: '🍊', type: 'emoji', name: 'Tangerine' },
    { content: '🍋', type: 'emoji', name: 'Lemon' },
    { content: '🍌', type: 'emoji', name: 'Banana' },
  ],
  cute: [
    { content: '🧸', type: 'emoji', name: 'Teddy Bear' },
    { content: '🐼', type: 'emoji', name: 'Panda' },
    { content: '🐨', type: 'emoji', name: 'Koala' },
    { content: '🐰', type: 'emoji', name: 'Rabbit' },
    { content: '🐱', type: 'emoji', name: 'Cat' },
    { content: '🐶', type: 'emoji', name: 'Dog' },
    { content: '🦄', type: 'emoji', name: 'Unicorn' },
    { content: '🦋', type: 'emoji', name: 'Butterfly' },
    { content: '🐝', type: 'emoji', name: 'Honeybee' },
    { content: '🐾', type: 'emoji', name: 'Paw Prints' },
    { content: '🦊', type: 'emoji', name: 'Fox' },
    { content: '🐻', type: 'emoji', name: 'Bear' },
    { content: '🐷', type: 'emoji', name: 'Pig' },
    { content: '🐸', type: 'emoji', name: 'Frog' },
    { content: '🐥', type: 'emoji', name: 'Front-Facing Baby Chick' },
    { content: '🐣', type: 'emoji', name: 'Hatching Chick' },
    { content: '🐦', type: 'emoji', name: 'Bird' },
    { content: '🐧', type: 'emoji', name: 'Penguin' },
    { content: '🦉', type: 'emoji', name: 'Owl' },
    { content: '🦇', type: 'emoji', name: 'Bat' },
    { content: '🐺', type: 'emoji', name: 'Wolf' },
    { content: '🐗', type: 'emoji', name: 'Boar' },
    { content: '🐴', type: 'emoji', name: 'Horse' },
    { content: '🦓', type: 'emoji', name: 'Zebra' },
    { content: '🦒', type: 'emoji', name: 'Giraffe' },
    { content: '🐘', type: 'emoji', name: 'Elephant' },
    { content: '🦏', type: 'emoji', name: 'Rhinoceros' },
    { content: '🦛', type: 'emoji', name: 'Hippopotamus' },
    { content: '🐭', type: 'emoji', name: 'Mouse' },
    { content: '🐹', type: 'emoji', name: 'Hamster' },
    { content: '🐰', type: 'emoji', name: 'Bunny' },
    { content: '🐱', type: 'emoji', name: 'Kawaii Cat' },
    { content: '🦁', type: 'emoji', name: 'Lion' },
    { content: '🐯', type: 'emoji', name: 'Tiger' },
    { content: '🐆', type: 'emoji', name: 'Leopard' },
    { content: '🐲', type: 'emoji', name: 'Dragon' },
    { content: '🦖', type: 'emoji', name: 'T-Rex' },
    { content: '🐙', type: 'emoji', name: 'Octopus' },
    { content: '🐬', type: 'emoji', name: 'Dolphin' },
    { content: '🐳', type: 'emoji', name: 'Whale' },
  ],
  emojis: [
    { content: '😊', type: 'emoji', name: 'Smiling Face' },
    { content: '😍', type: 'emoji', name: 'Heart Eyes' },
    { content: '😎', type: 'emoji', name: 'Cool' },
    { content: '😇', type: 'emoji', name: 'Angel' },
    { content: '🥺', type: 'emoji', name: 'Pleading Face' },
    { content: '😂', type: 'emoji', name: 'Laughing' },
    { content: '🥰', type: 'emoji', name: 'Loving Face' },
    { content: '🤩', type: 'emoji', name: 'Star-Struck' },
    { content: '🥳', type: 'emoji', name: 'Partying Face' },
    { content: '😌', type: 'emoji', name: 'Relieved Face' },
    { content: '😋', type: 'emoji', name: 'Savoring Food' },
    { content: '😛', type: 'emoji', name: 'Face with Tongue' },
    { content: '😜', type: 'emoji', name: 'Winking Face with Tongue' },
    { content: '🤪', type: 'emoji', name: 'Zany Face' },
    { content: '🤨', type: 'emoji', name: 'Face with Raised Eyebrow' },
    { content: '🧐', type: 'emoji', name: 'Face with Monocle' },
    { content: '🤓', type: 'emoji', name: 'Nerd Face' },
    { content: '😎', type: 'emoji', name: 'Smiling Face with Sunglasses' },
    { content: '🥸', type: 'emoji', name: 'Disguised Face' },
    { content: '🤩', type: 'emoji', name: 'Starry Eyes' },
    { content: '🥳', type: 'emoji', name: 'Celebration' },
    { content: '😏', type: 'emoji', name: 'Smirking Face' },
    { content: '😒', type: 'emoji', name: 'Unamused Face' },
    { content: '😞', type: 'emoji', name: 'Disappointed Face' },
    { content: '😔', type: 'emoji', name: 'Pensive Face' },
    { content: '😟', type: 'emoji', name: 'Worried Face' },
    { content: '😕', type: 'emoji', name: 'Confused Face' },
    { content: '🙁', type: 'emoji', name: 'Slightly Frowning Face' },
    { content: '☹️', type: 'emoji', name: 'Frowning Face' },
    { content: '😣', type: 'emoji', name: 'Persevering Face' },
    { content: '😖', type: 'emoji', name: 'Confounded Face' },
    { content: '😫', type: 'emoji', name: 'Tired Face' },
    { content: '😩', type: 'emoji', name: 'Weary Face' },
    { content: '🥺', type: 'emoji', name: 'Begging Face' },
    { content: '😢', type: 'emoji', name: 'Crying Face' },
    { content: '😭', type: 'emoji', name: 'Loudly Crying Face' },
    { content: '😤', type: 'emoji', name: 'Face with Steam From Nose' },
    { content: '😠', type: 'emoji', name: 'Angry Face' },
    { content: '😡', type: 'emoji', name: 'Pouting Face' },
    { content: '🤬', type: 'emoji', name: 'Face with Symbols on Mouth' },
  ],
  objects: [
    { content: '🍓', type: 'emoji', name: 'Strawberry' },
    { content: '🍒', type: 'emoji', name: 'Cherries' },
    { content: '🥑', type: 'emoji', name: 'Avocado' },
    { content: '☕', type: 'emoji', name: 'Coffee' },
    { content: '🍕', type: 'emoji', name: 'Pizza' },
    { content: '✈️', type: 'emoji', name: 'Airplane' },
    { content: '🎵', type: 'emoji', name: 'Musical Note' },
    { content: '🎮', type: 'emoji', name: 'Video Game' },
    { content: '🍔', type: 'emoji', name: 'Hamburger' },
    { content: '🍟', type: 'emoji', name: 'French Fries' },
    { content: '🌭', type: 'emoji', name: 'Hot Dog' },
    { content: '🌮', type: 'emoji', name: 'Taco' },
    { content: '🍦', type: 'emoji', name: 'Soft Ice Cream' },
    { content: '🍩', type: 'emoji', name: 'Doughnut' },
    { content: '🍪', type: 'emoji', name: 'Cookie' },
    { content: '🧁', type: 'emoji', name: 'Cupcake' },
    { content: '🍰', type: 'emoji', name: 'Shortcake' },
    { content: '🍫', type: 'emoji', name: 'Chocolate Bar' },
    { content: '🍬', type: 'emoji', name: 'Candy' },
    { content: '🍭', type: 'emoji', name: 'Lollipop' },
    { content: '🍹', type: 'emoji', name: 'Tropical Drink' },
    { content: '🍺', type: 'emoji', name: 'Beer Mug' },
    { content: '🍷', type: 'emoji', name: 'Wine Glass' },
    { content: '🥤', type: 'emoji', name: 'Cup with Straw' },
    { content: '🧋', type: 'emoji', name: 'Bubble Tea' },
    { content: '🍱', type: 'emoji', name: 'Bento Box' },
    { content: '🍣', type: 'emoji', name: 'Sushi' },
    { content: '🍜', type: 'emoji', name: 'Steaming Bowl' },
    { content: '🍙', type: 'emoji', name: 'Rice Ball' },
    { content: '🥐', type: 'emoji', name: 'Croissant' },
    { content: '🥨', type: 'emoji', name: 'Pretzel' },
    { content: '🥞', type: 'emoji', name: 'Pancakes' },
    { content: '🧇', type: 'emoji', name: 'Waffle' },
    { content: '🧀', type: 'emoji', name: 'Cheese Wedge' },
    { content: '🍳', type: 'emoji', name: 'Cooking' },
    { content: '🥓', type: 'emoji', name: 'Bacon' },
    { content: '🥪', type: 'emoji', name: 'Sandwich' },
    { content: '🥗', type: 'emoji', name: 'Green Salad' },
    { content: '🍿', type: 'emoji', name: 'Popcorn' },
    { content: '🥫', type: 'emoji', name: 'Canned Food' },
  ],
  aesthetic: [
    { content: '✨', type: 'emoji', name: 'Sparkles' },
    { content: '⭐', type: 'emoji', name: 'Star' },
    { content: '💫', type: 'emoji', name: 'Dizzy' },
    { content: '🌈', type: 'emoji', name: 'Rainbow' },
    { content: '🌙', type: 'emoji', name: 'Crescent Moon' },
    { content: '☁️', type: 'emoji', name: 'Cloud' },
    { content: '☀️', type: 'emoji', name: 'Sun' },
    { content: '🌊', type: 'emoji', name: 'Water Wave' },
    { content: '💎', type: 'emoji', name: 'Gem Stone' },
    { content: '💍', type: 'emoji', name: 'Ring' },
    { content: '💄', type: 'emoji', name: 'Lipstick' },
    { content: '💅', type: 'emoji', name: 'Nail Polish' },
    { content: '👗', type: 'emoji', name: 'Dress' },
    { content: '👠', type: 'emoji', name: 'High-Heeled Shoe' },
    { content: '👜', type: 'emoji', name: 'Handbag' },
    { content: '🕶️', type: 'emoji', name: 'Sunglasses' },
    { content: '👒', type: 'emoji', name: 'Woman’s Hat' },
    { content: '🧣', type: 'emoji', name: 'Scarf' },
    { content: '🧤', type: 'emoji', name: 'Gloves' },
    { content: '🧥', type: 'emoji', name: 'Coat' },
    { content: '🧸', type: 'emoji', name: 'Aesthetic Bear' },
    { content: '💌', type: 'emoji', name: 'Love Letter' },
    { content: '💘', type: 'emoji', name: 'Heart with Arrow' },
    { content: '💝', type: 'emoji', name: 'Heart with Ribbon' },
    { content: '💖', type: 'emoji', name: 'Sparkling Heart' },
    { content: '💗', type: 'emoji', name: 'Growing Heart' },
    { content: '💓', type: 'emoji', name: 'Beating Heart' },
    { content: '💞', type: 'emoji', name: 'Revolving Hearts' },
    { content: '💕', type: 'emoji', name: 'Two Hearts' },
    { content: '💟', type: 'emoji', name: 'Heart Decoration' },
    { content: '❣️', type: 'emoji', name: 'Heart Exclamation' },
    { content: '💔', type: 'emoji', name: 'Broken Heart' },
    { content: '❤️‍🔥', type: 'emoji', name: 'Heart on Fire' },
    { content: '❤️‍🩹', type: 'emoji', name: 'Mending Heart' },
    { content: '❤️', type: 'emoji', name: 'Red Heart' },
    { content: '🧡', type: 'emoji', name: 'Orange Heart' },
    { content: '💛', type: 'emoji', name: 'Yellow Heart' },
    { content: '💚', type: 'emoji', name: 'Green Heart' },
    { content: '💙', type: 'emoji', name: 'Blue Heart' },
    { content: '💜', type: 'emoji', name: 'Purple Heart' },
  ],
  trendy: [
    { content: '🔥', type: 'emoji', name: 'Fire' },
    { content: '⚡', type: 'emoji', name: 'Voltage' },
    { content: '💥', type: 'emoji', name: 'Collision' },
    { content: '🚀', type: 'emoji', name: 'Rocket' },
    { content: '🛸', type: 'emoji', name: 'Flying Saucer' },
    { content: '👾', type: 'emoji', name: 'Alien Monster' },
    { content: '👽', type: 'emoji', name: 'Alien' },
    { content: '👻', type: 'emoji', name: 'Ghost' },
    { content: '💀', type: 'emoji', name: 'Skull' },
    { content: '🤖', type: 'emoji', name: 'Robot' },
    { content: '🎃', type: 'emoji', name: 'Jack-O-Lantern' },
    { content: '🕸️', type: 'emoji', name: 'Spider Web' },
    { content: '🕷️', type: 'emoji', name: 'Spider' },
    { content: '🦂', type: 'emoji', name: 'Scorpion' },
    { content: '🧛', type: 'emoji', name: 'Vampire' },
    { content: '🧟', type: 'emoji', name: 'Zombie' },
    { content: '🧞', type: 'emoji', name: 'Genie' },
    { content: '🧜', type: 'emoji', name: 'Merman/Mermaid' },
    { content: '🧚', type: 'emoji', name: 'Fairy' },
    { content: '🦄', type: 'emoji', name: 'Trendy Unicorn' },
    { content: '🐲', type: 'emoji', name: 'Dragon Head' },
    { content: '🐉', type: 'emoji', name: 'Dragon' },
    { content: '🦖', type: 'emoji', name: 'Dinosaur' },
    { content: '🦕', type: 'emoji', name: 'Sauropod' },
    { content: '🐢', type: 'emoji', name: 'Turtle' },
    { content: '🐍', type: 'emoji', name: 'Snake' },
    { content: '🦎', type: 'emoji', name: 'Lizard' },
    { content: '🦖', type: 'emoji', name: 'T-Rex' },
    { content: '🦕', type: 'emoji', name: 'Diplodocus' },
    { content: '🦑', type: 'emoji', name: 'Squid' },
    { content: '🦞', type: 'emoji', name: 'Lobster' },
    { content: '🦀', type: 'emoji', name: 'Crab' },
    { content: '🐡', type: 'emoji', name: 'Blowfish' },
    { content: '🐠', type: 'emoji', name: 'Tropical Fish' },
    { content: '🐟', type: 'emoji', name: 'Fish' },
    { content: '🦈', type: 'emoji', name: 'Shark' },
    { content: '🐳', type: 'emoji', name: 'Spouting Whale' },
    { content: '🐋', type: 'emoji', name: 'Whale' },
    { content: '🐊', type: 'emoji', name: 'Crocodile' },
    { content: '🐅', type: 'emoji', name: 'Tiger' },
  ],
  text: [
    { content: 'Good Vibes', type: 'text', font: 'Poppins', color: '#ff6b6b' },
    { content: 'Stay Cool', type: 'text', font: 'Inter', color: '#4ecdc4' },
    { content: 'Dream Big', type: 'text', font: 'Cursive', color: '#6c5ce7' },
    { content: 'Be Happy', type: 'text', font: 'Poppins', color: '#ffd93d' },
    { content: 'Keep Going', type: 'text', font: 'Inter', color: '#ff8c42' },
    { content: 'Love Yourself', type: 'text', font: 'Poppins', color: '#fd79a8' },
    { content: 'Stay Wild', type: 'text', font: 'Cursive', color: '#00b894' },
    { content: 'Magic', type: 'text', font: 'Poppins', color: '#a29bfe' },
    { content: 'Forever', type: 'text', font: 'Inter', color: '#fab1a0' },
    { content: 'Glow', type: 'text', font: 'Poppins', color: '#ffeaa7' },
  ]
};
